plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.chatbot'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.ai:spring-ai-bom:1.1.0-M1-PLATFORM-2'
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.ai:spring-ai-google-genai:1.1.0-M1-PLATFORM-2'
	implementation 'org.springframework.ai:spring-ai-google-genai-embedding:1.1.0-M1-PLATFORM-2'
	implementation 'org.springframework.ai:spring-ai-autoconfigure-model-google-genai:1.1.0-M1-PLATFORM-2'
	implementation 'org.springframework.ai:spring-ai-autoconfigure-model-chat-client'
	implementation 'org.springframework.ai:spring-ai-vector-store'
	implementation 'org.springframework.ai:spring-ai-tika-document-reader'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
